### ISSUE TITLE
Require function doesn't work

### ISSUE THREAD

**Issue by balous** [seznam/goenvtemplator#10]
I am unable to make ```require``` to do what documentation states:

```
petr@baloun-petr:~$ cat ./required.tmpl 
jen pockej, {{ require (env "kdo") }}
petr@baloun-petr:~$ set | grep kdo ; goenvtemplator2 -template `pwd`/required.tmpl:/dev/stdout
jen pockej, 
petr@baloun-petr:~$
```

BTW, there is missing apostrophes in the documentation example:
```
{{ require (env "TIMEOUT_MS) }}
```

**Comment by dohnto** [comment]
This has no priority for us right now. Not working on this for at least next 2 weeks. Will be back soon.

**Comment by dohnto** [comment]
Closing via #15.
