### ISSUE TITLE
Problem with substituting string with apostrophes

### ISSUE THREAD

**Issue by balous** [seznam/goenvtemplator#11]
It seems that goenvtemplator removes apostrophes that are on the beginning and end of substitution string (env variable). I am generating with env file:

```
goenvtemplator2 --env-file conf/production.env -template `pwd`/conf/metaserver.conf.tmpl:/dev/stdout
```

The env file has following content:

```
POISERVER_WEBCAM_TIME_FORMAT="%H:%M"
POISERVER_WEBCAM_TIME_START='"08:00"'
POISERVER_WEBCAM_TIME_STOP=' "16:30" '
```

The template:

```
webcamTimeFormat = {{ env "POISERVER_WEBCAM_TIME_FORMAT" | default "\"%H:%M\"" }}
webcamTimeStart  = {{ env "POISERVER_WEBCAM_TIME_START"  | default "\"08:00\"" }}
webcamTimeStop   = {{ env "POISERVER_WEBCAM_TIME_STOP"   | default "\"16:30\"" }}

```

The result:

```
webcamTimeFormat = %H:%M
webcamTimeStart  = 08:00
webcamTimeStop   =  "16:30" 
```

Notice that apostrophes survived just on the last line, where they are surrounded by single apostrophes and spaces.

**Comment by dohnto** [comment]
This has no priority for us right now. Not working on this for at least next 2 weeks. Will be back soon.

**Comment by FUSAKLA** [comment]
I can't reproduce it with current master having
```
test=bla
test1='"bla"'
test2=""bla""
test3="'bla'"
test4=''bla''
```
```
{{ env "test" }}
{{ env "test1" }}
{{ env "test2" }}
{{ env "test3" }}
{{ env "test4" }}
```
resulting in
```
bla
"bla"
"bla"
'bla'
'bla'
```
Which seems to me ok?

**Comment by dohnto** [comment]
It is (see below) for me. You probably already have never version of godotenv. Be sure to have `https://github.com/seznam/goenvtemplator/blob/master/glide.lock#L7` this version.
```
$ ./goenvtemplator2 -env-file a -template $PWD/b:/dev/stdout
bla
bla
""bla""
bla
''bla''
```

**Comment by dohnto** [comment]
@balous, If you can still reproduce, please reopen this issue.
